service: amazon-tax-pro
image: gradeycullins/amazon-tax-pro
servers:
  web:
    - hetzner

proxy:
  ssl: true
  host: amazontaxpro.com
  app_port: 3000

registry:
  username: gradeycullins
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    TZ: America/Denver
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY

aliases:
  shell: app exec --interactive --reuse "bash"

ssh:
  user: gb

volumes:
  - "amazon_tax_pro_storage:/rails/storage"
